name: auto_build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: 11
      - uses: subosito/flutter-action@v2.1.0
        with:
            channel: 'stable'
      - run: apt install build-essential ninja-build
      - run: flutter pub get
      - run: flutter build linux
      - run: tar cfz linux.tar.gz build/linux/release/
      - uses: actions/upload-artifact@master
        with:
          name: fluttervcc_amd64_linux.tar.gz
          path: linux.tar.gz
